name: Build and Test
on:
  pull_request:
    branches:
      - main
  push: 

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          ref: "${{ github.ref }}"
      - uses: actions/cache@v3
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install package dependencies and playwright
        run: |
          yarn
          yarn playwright install chromium --with-deps

      - name: Build the app 
        run: yarn build

      - name: Run unit tests
        run: yarn test:unit --verbose

      - name: Run e2e tests with Playwright
        run: yarn test:e2e:ci

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 4
